language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - cython
      # The following as required for netcdf files:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
install:
    - USE_SETUPCFG=0 HDF5_INCDIR=/usr/include/hdf5/serial HDF5_LIBDIR=/usr/lib/x86_64-linux-gnu/hdf5/serial pip install netcdf4-python
    # Continue typical install:
    - travis_wait 30 pip install scipy
    - pip install -e .[testing,functions,tests]

script:
    - python setup.py nosetests -a '!auth'
