language: python
python: 2.7
virtualenv:
    system_site_packages: true
branches:
    only:
        - toxify

before_install:
    - sudo apt-get install -qq python-numpy python-scipy
install:
    - pip install tox

env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33

script:
    - tox -e $TOX_ENV
