language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - cython
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
install:
    - nc-config --all
    - export USE_NCONFIG=1; pip install netcdf4
    - travis_wait 30 pip install scipy
    - pip install -e .[testing,functions,tests]

script:
    - python setup.py nosetests -a '!auth'
