language: python
python: 2.7
install:
  - "pip install -e .[testing] --use-mirrors"
branches:
  only:
      - toxify
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33

script:
    - tox -e $TOX_ENV