language: python

sudo: false

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6

install:
    - pip install scipy
    - pip install -e .[testing,functions,tests]

script:
    - python setup.py nosetests -a '!auth'
    - if [ "${TRAVIS_PYTHON_VERSION}" == 3.5 ]; then flake8; fi
