language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -e .[testing_extras] --use-mirrors"
  - "pip install coverage WebTest --use-mirrors"
script: nosetests
branches:
  only:
      - develop
