language: python
python:
  - "2.6"
  - "2.7"
addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - cython
install:
  - "pip install -e .[testing]"
script: nosetests
